version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/BaiduExporter

    branches:
      only:
        - dev

    steps:
      - run: sudo apt update
      # add xxd dependency
      - run: sudo apt-get install -y vim-common
      - checkout
      - restore_cache:
          keys:
            - node-chache-{{ .Branch }}-{{ checksum "chrome/package-lock.json" }}
            - node-chache-{{ .Branch }}-
            - node-chache-
      - run: npm --prefix chrome install
      - save_cache:
          key: node-chache-{{ .Branch }}-{{ checksum "chrome/package-lock.json" }}
          paths:
            - chrome/node_modules/
      - run: npm --prefix chrome run build
      - run: echo -e $KEY > /tmp/key.pem
      - run: .circleci/pack chrome/dist /tmp/key.pem

      - run: |
          git config --global user.email "acgotaku311@gmail.com"
          git config --global user.name "acgotaku311"
          git add BaiduExporter.crx
          git commit -m "[ci skip] update chrome.crx"
          git push --set-upstream origin dev
